WINDOW_SIZE = 1024
LOCAL_MAX_WINDOW = 3  # window used to find a local maximum
LOCAL_MEAN_RANGE_MULTIPLIER = 3
LOCAL_MEAN_THRESHOLD = 55000
EXPONENTIAL_DECAY_THRESHOLD_PARAMETER = 0.72

RING_BUFFER_SIZE = 40
SAMPLE_RATE = 44100

TUNE_HYPERPARAMETERS = False

SOUNDFONT = "sound_fonts/SpanishClassicalGuitar.sf2"
# don't set it to False, broke it right now
FROM_FILE = True
